### ISSUE TITLE
make a release or add a tag for easier reference

### ISSUE THREAD

**Issue by dmitris** [DeedleFake/xiter#7]
@DeedleFake could you make a release (even if `v0.0.1` or whatever) or add a semver-compatible flag so that it would be easier to reference the library when experimenting with or using it? Thanks! 😄

**Comment by DeedleFake** [comment]
I've had a lot of backwards incompatible changes, but I suppose that I could do that, yeah. Just didn't really feel like it was stable enough quite yet.

**Comment by DeedleFake** [comment]
Done.
