### ISSUE TITLE
Chunking a map

### ISSUE THREAD

**Issue by dolzenko** [DeedleFake/xiter#8]
Nice lib, thanks for sharing! :heart: 
Wanted to discuss this - I want to chunk a big map in a way so that I'm yielded sequences of (k, v) chunks, what is the best way to do this? Currently the closest thing I came up with is something like

```go
for keys := range xiter.Chunks(maps.Keys(bigMap), 1000) {
	batch := make([]batchElem, 0)
	for k, v := range KeysValuesAt(all, slices.Values(keys)) {
		batch = append(batch, batchElem{k: k, v: v})
	}
	// do something with batch
}

func KeysValuesAt[Map ~map[K]V, K comparable, V any](m Map, seq iter.Seq[K]) iter.Seq2[K, V] {
	return func(yield func(K, V) bool) {
		for k := range seq {
			if !yield(k, m[k]) {
				return
			}
		}
	}
}
```

but it seems there must be simpler way and without allocation?

**Comment by DeedleFake** [comment]
Thank you.

You could chunk key/value pairs instead of just keys:

```go
chunks := xiter.Chunks(xiter.ToPair(maps.All(bigMap)), 1000)
for chunk := range chunks {
  // chunk is now an []xiter.Pair[K, V] where K and V are the key and value types.
}
```

What's the use case, though? Unless you're doing something specific, this is less efficient than just looping through the map one element at a time.

**Comment by dolzenko** [comment]
@DeedleFake thanks again, the use case is simple, I'm doing batched send to the API, but the data I need to send must be collected in the map first.
